### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by ShellOn** [audiokit/AudioKit#210]
Neither the Static library or dynamic library i can compiled...  the error 

```
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang", line 63, in <module>
    output, err = process.communicate()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 798, in communicate
    return self._communicate(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1402, in _communicate
    stdout, stderr = self._communicate_with_select(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1503, in _communicate_with_select
    rlist, wlist, xlist = select.select(read_set, write_set, [])

KeyboardInterrupt Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1
```

i am using XCode 6.4 (6E35B) , have set the -ObjC flag and /AudioKit/AudioKit for 
 User Header Search Paths

**Comment by aure** [comment]
Unfortunately this is not really actionable without more information.  If you would like to share your project or your screen, we could help you debug this.
